# ************************** BEGIN LICENSE BLOCK ******************************
#
# Copyright © 2023 Christian Stolze
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ************************** END LICENSE BLOCK ********************************

# This Dockerfile describes the containerization of the Renderhive Service App's frontend for development (hot reloading enabled)

# Build the React application
FROM node:18-alpine as builder

# Set working directory to the source code
WORKDIR /usr/src/app

# Install dependencies and build static assets
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

# Start the development server
CMD ["npm", "run", "dev"]