# ************************** BEGIN LICENSE BLOCK ******************************
#
# Copyright © 2023 Christian Stolze
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ************************** END LICENSE BLOCK ********************************

# Docker-compose file for the active development. Enables hot reloading for both the backend end frontend.

version: '3'

services:
  backend_dev:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    user: "renderhive"
    ports:
      # NOTE: The specification of the IP address is important here, since we bind vite to "0.0.0.0"
      #       If not specified, other machines could access the web app (if the firewall rules would allow for that)
      - "127.0.0.1:5174:5174"
    volumes:
      - ./backend/src:/app
      - config:/app/config
      - data:/app/data
    networks:
      - renderhive-container-network

  frontend_dev:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    user: "renderhive"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      # NOTE: The specification of the IP address is important here, since we bind vite to "0.0.0.0"
      #       If not specified, other machines could access the web app (if the firewall rules would allow for that)
      - "127.0.0.1:5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend_dev
    networks:
      - renderhive-container-network

# NETWORK CONFIGURATION
networks:
  renderhive-container-network:
    driver: bridge

# VOLUME CONFIGURATION
volumes:
  config:
    labels:
      project-name: "Renderhive"
      project-version: "0.0.1"

  data:
    labels:
      project-name: "Renderhive"
      project-version: "0.0.1"